# -*- coding: utf-8 -*-
"""quality_control.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T5LKB-JNjzBfP9EiNEZleBysWEcnDyp1
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/Shareddrives/BIO485/data_dir/fastQC_analysis
# %ls

import condacolab

!conda install -c bioconda trim-galore 
!conda install -c bioconda cutadapt

!unzip fastqc_v0.11.7.zip

# Commented out IPython magic to ensure Python compatibility.
!chmod 755 FastQC
# %cd FastQC/

# Commented out IPython magic to ensure Python compatibility.
!chmod 755 fastqc
# %ls -lh

# Run fastqc for quality control of all 6 data sets --> all good scores (no low quality bp + no adapters)
!FastQC/fastqc ../samples/ERR5684197.fastq
!FastQC/fastqc ../samples/ERR5684198.fastq
!FastQC/fastqc ../samples/ERR5684199.fastq
!FastQC/fastqc ../samples/ERR5684200.fastq
!FastQC/fastqc ../samples/ERR5684201.fastq
!FastQC/fastqc ../samples/ERR5684202.fastq